server:
  port: 9527
spring:
  application:
    name: zuul
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
zuul:
  prefix: /kunluntop
  ignored-services: "*"
  routes:
    mydept.serviceId: carsystem
    mydept.path: /car/**